.init_ssh: &init_ssh |
  eval $(ssh-agent -s)
  echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  
.init_ssh2: &init_ssh2 |
  eval $(ssh-agent -s)
  chmod 700 "$PRIVATE_KEY"
  ls -la "$PRIVATE_KEY"
  ssh-add "$PRIVATE_KEY" > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

stages:
  - build
  - deploy


build_job:
  image: registry.git.or.rwth-aachen.de/docker/gcg-doc:latest
  stage: build
  artifacts:
    paths:
      - static/build/
      - webpack-stats.json
      - .cache/pip
  before_script:
      - *init_ssh2
      - git submodule sync --recursive
      - git submodule update --init --recursive
      - cd lib
      - ln -s scip-git scip
      - ln -s bliss-git bliss
      - cd ..
  script:
      - make soplex
      - cd lib/scip/lib
      - mkdir include
      - ln -s ../../../soplex-git/src/ include/spxinc
      - mkdir static
      - ln -s ../../../soplex-git/lib/libsoplex.linux.x86_64.gnu.opt.a static/libsoplex.linux.x86_64.gnu.opt.a
      - cd ../../../
      - make ZIMPL=false
      - make doc
#  only:
#    - tags
#    - merge_requests


#deploy_production:
#  image: pivotaldata/concourse-ssh
#  stage: deploy
#  dependencies: 
#    - build_job
#  environment:
#    name: Production
#    url: https://orweb.or.rwth-aachen.de
#  only:
#    - tags
#  except:
#    - branches
#  before_script:
#    - *init_ssh
#  script:
#    - echo "Deploying tag $CI_COMMIT_TAG ..."
#    # copy new data to dev
#    - scp -r doc/html gitGCGdoc@orweb.or.rwth-aachen.de:/var/www/gcg-doc-dev
#    - ssh gitGCGdoc@orweb.or.rwth-aachen.de "cd /var/www/gcg-doc-dev; chmod 744 ./* ;"