# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script: 
  #   - apt update && apt -y install make autoconf 
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script: 
    - test -L lib/scip || ln -s scip-git lib/scip
    - pushd lib/soplex-git
    - make
    - popd
    - mkdir -p  lib/scip/lib
    - mkdir -p lib/scip/lib/include lib/scip/lib/static lib/scip/lib/shared
    - test -L lib/scip/lib/cpxinc || ln -s /opt/cplex/cplex/include/ilcplex/ lib/scip/lib/cpxinc
    - test -L lib/scip/lib/include/cpxinc || ln -s /opt/cplex/cplex/include/ilcplex/ lib/scip/lib/include/cpxinc
    - test -L lib/scip/lib/libcplex.linux.x86_64.gnu.a || ln -s /opt/cplex/cplex/lib/x86-64_sles10_4.1/static_pic/libcplex.a lib/scip/lib/libcplex.linux.x86_64.gnu.a
    - test -L lib/scip/lib/static/libcplex.linux.x86_64.gnu.a || ln -s /opt/cplex/cplex/lib/x86-64_sles10_4.1/static_pic/libcplex.a lib/scip/lib/static/libcplex.linux.x86_64.gnu.a
    - test -L lib/scip/lib/libzimpl.linux.x86_64.gnu.opt.a || ln -s /opt/scipoptsuite-3.0.2/zimpl-3.3.1/lib/libzimpl.linux.x86_64.gnu.opt.a lib/scip/lib/libzimpl.linux.x86_64.gnu.opt.a
    - test -L lib/scip/lib/static/libzimpl.linux.x86_64.gnu.opt.a || ln -s /opt/scipoptsuite-3.0.2/zimpl-3.3.1/lib/libzimpl.linux.x86_64.gnu.opt.a lib/scip/lib/static/libzimpl.linux.x86_64.gnu.opt.a
    - mkdir -p lib/scip/lib/zimplinc
    - mkdir -p lib/scip/lib/include/zimplinc
    - test -L lib/scip/lib/zimplinc/zimpl || ln -s /opt/scipoptsuite-3.0.2/zimpl-3.3.1/src/ lib/scip/lib/zimplinc/zimpl
    - test -L lib/scip/lib/include/zimplinc/zimpl || ln -s /opt/scipoptsuite-3.0.2/zimpl-3.3.1/src/ lib/scip/lib/include/zimplinc/zimpl
    - test -L lib/scip/lib/spxinc || ln -s ../../soplex-git/src/ lib/scip/lib/spxinc
    - rm lib/scip/lib/include/spxinc
    - test -L lib/scip/lib/include/spxinc || ln -s ../../../soplex-git/src/ lib/scip/lib/include/spxinc
    - rm lib/scip/lib/static/libsoplex.linux.x86_64.gnu.opt.a
    - test -L lib/scip/lib/libsoplex.linux.x86_64.gnu.opt.a || ln -s ../../soplex-git/lib/libsoplex.a lib/scip/lib/libsoplex.linux.x86_64.gnu.opt.a
    - test -L lib/scip/lib/static/libsoplex.linux.x86_64.gnu.opt.a || ln -s ../../../soplex-git/lib/libsoplex.a lib/scip/lib/static/libsoplex.linux.x86_64.gnu.opt.a
    - touch lib/scip/lib/linkscreated.cpx-opt.linux.x86_64.gnu.true-opt.false-opt.none
    - touch lib/scip/lib/linkscreated.cpx-opt.linux.x86_64.gnu.true-opt.false-opt
    - touch lib/scip/lib/linkscreated.spx-opt.linux.x86_64.gnu.true-opt.false-opt.none
    - touch lib/scip/lib/linkscreated.spx-opt.linux.x86_64.gnu.true-opt.false-opt
    - touch lib/scip/lib/linkscreated.spx-opt.linux.x86_64.gnu.true-opt.false-opt.false
    - touch lib/scip/lib/linkscreated.cpx-opt.linux.x86_64.gnu.true-opt.false-opt.false
    - make googletest
    - test -L lib/blissinc || ln -s bliss lib/blissinc 
    - test -L lib/libbliss.a || ln -s blissinc/libbliss.a lib/libbliss.a
    - test -L lib/gtest || ln -s googletest/include lib/gtest
    - test -L lib/libgtest.a || ln -s googletest/build/libgtest.a lib/libgtest.a
    - touch lib/linkscreated.true.true
    - touch lib/linkscreated.true.false
    - make OPT=dbg CPLEXSOLVER=false PARASCIP=true scip_clean
    - make OPT=dbg CPLEXSOLVER=false PARASCIP=true scip
    - make bliss
    - make OPT=dbg CPLEXSOLVER=false PARASCIP=true
    - make googletest
    - make OPT=dbg CPLEXSOLVER=false PARASCIP=true tests
#     - bin/gcg_test 2>/dev/null
  artifacts:
    paths:
      - mybinary
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - bin/gcg_test
