# GCG Gitlab CI script

.init_ssh2: &init_ssh2 |
  eval $(ssh-agent -s)
  chmod 700 "$PRIVATE_KEY"
  ls -la "$PRIVATE_KEY"
  ssh-add "$PRIVATE_KEY" > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

stages:
  - build
  - test
  - documentation

default:
  image: registry.git.or.rwth-aachen.de/docker/gcg-doc:latest
  script: 
    - *init_ssh2
    - git submodule sync --recursive
    - git submodule update --init --recursive

cmake:
  stage: build
  before_script:
    - mkdir build
    - cd build
  script:
    - cmake ..
    - make -j 4
    - cd ..

make:
  stage: build
  script:
    - make deps
    - make

make_test:
  stage: test
  dependencies:
    - build
  script:
    - make test

cmake_test:
  stage: test
  dependencies:
    - build
  before_script:
    - cd build
  script:
    - make gcg_test

docu:
  stage: docu_build
  dependencies:
    - build
  before_script:
    - cd documentation
  script:
    - make gcg_doc -j 4
    - cd ..
    # upload documentation to gcg.or.rwth-aachen.de/dev
    #- scp -r doc/html/. gitGCGdoc@orweb.or.rwth-aachen.de:/var/www/gcg-doc-dev
    #- ssh gitGCGdoc@orweb.or.rwth-aachen.de "cd /var/www/gcg-doc-dev; chmod -R 755 ./* ; "