# GCG Gitlab CI script
.init_ssh2: &init_ssh2 |
  eval $(ssh-agent -s)
  chmod 700 "$PRIVATE_KEY"
  ls -la "$PRIVATE_KEY"
  ssh-add "$PRIVATE_KEY" > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

stages:
  - build
  - test
  - documentation

# default, loaded with docker image for Linux
default:
  image: registry.git.or.rwth-aachen.de/docker/gcg-doc:latest
  before_script:
    # initialize SSH key to access repositories 
    - *init_ssh2
    # update submodules
    - git submodule sync --recursive
    - git submodule update --init --recursive
    # set links to SCIP and SoPLEX  # SCIP link in GCG folder
    - ln -s ../lib/scip-git lib/scip
    # SoPlex links inside SCIP lib folder
    - mkdir -p lib/scip/lib/include/spxinc
    - ln -s $PWD/lib/soplex-git/src/* $PWD/lib/scip/lib/include/spxinc/
    - mkdir -p lib/scip/lib/static/
    - ln -s $PWD/lib/soplex-git/lib/libsoplex.linux.x86_64.gnu.opt.a $PWD/lib/scip/lib/static/libsoplex.linux.x86_64.gnu.opt.a

# CMake compilation job
cmake:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j 4
    - cd ..
  artifacts:
    paths:
      - MAKEFILE
      - build/
      - check/
      - lib/
    expire_in: 2 hours

# Make compilation job
make:
  stage: build
  script:
    - make deps
    - make
  artifacts:
    paths:
      - MAKEFILE
      - bin/
      - check/
      - lib/
    expire_in: 2 hours

# CMake test (test set: short)
cmake_test:
  stage: test
  dependencies:
    - cmake
  before_script:
    - cd build
  script:
    - make gcg_test

# Makefiles test (test set: short)
make_test:
  stage: test
  inherit:
    default: false
  dependencies:
    - make
  script:
    - make test

# Compile documentation and upload to website
docu:
  stage: documentation
  dependencies:
    - cmake
  before_script:
    - cd build
  script:
    - make gcg_doc -j 4
    - cd ..
    # upload documentation to gcg.or.rwth-aachen.de/dev
    #- scp -r doc/html/. gitGCGdoc@orweb.or.rwth-aachen.de:/var/www/gcg-doc-dev
    #- ssh gitGCGdoc@orweb.or.rwth-aachen.de "cd /var/www/gcg-doc-dev; chmod -R 755 ./* ; "