# GCG Gitlab CI script
.init_ssh2: &init_ssh2 |
  eval $(ssh-agent -s)
  chmod 700 "$PRIVATE_KEY"
  ls -la "$PRIVATE_KEY"
  ssh-add "$PRIVATE_KEY" > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

stages:
  - build
  - test
  - documentation
  - report

# default, loaded with docker image for Linux
default:
  image: registry.git.or.rwth-aachen.de/docker/gcg-doc:latest
  before_script:
    # initialize SSH key to access repositories 
    - *init_ssh2
    # update submodules
    - git submodule sync --recursive
    - git submodule update --init --recursive
    # set links to SCIP and SoPLEX
    - ln -sfn ../lib/scip-git lib/scip
    # SoPlex links inside SCIP lib folder
    - mkdir -p lib/scip/lib/include/spxinc
    - ln -sfn $PWD/lib/soplex-git/src/* $PWD/lib/scip/lib/include/spxinc/
    - mkdir -p lib/scip/lib/static/
    - ln -sfn $PWD/lib/soplex-git/lib/libsoplex.linux.x86_64.gnu.opt.a $PWD/lib/scip/lib/static/libsoplex.linux.x86_64.gnu.opt.a

# CMake compilation job
cmake:build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j 4
    - cd ..
  artifacts:
    expire_in: 1 hour
    when: on_success
    paths:
      - $CI_PROJECT_DIR

# Make compilation job
make:build:
  stage: build
  script:
    - make deps
    - make
    - mkdir -p lib/include
    - mkdir -p lib/static
    ## Cliquer ##
    # obtain
    - wget http://users.aalto.fi/~pat/cliquer/cliquer-1.21.tar.gz
    - tar xvfz cliquer-1.21.tar.gz
    - ln -sfn ../cliquer-1.21/ lib/cliquer-git
    # link & compile
    - ln -sfn ../cliquer-git/ lib/include/cliquer
    - make cliquer
    - ln -sfn ../cliquer-git/libcliquer.a lib/static/libcliquer.a
    - make deps CLIQUER=true
    - make CLIQUER=true
    ## Bliss ##
    # link & compile
    - make bliss
    - ln -sfn ../bliss-git lib/include/bliss
    - ln -sfn ../bliss-git/libbliss.a lib/static/libbliss.a
    - make deps CLIQUER=true BLISS=true
    - make CLIQUER=true BLISS=true
    ## hMetis ##
    # link
    - wget http://glaros.dtc.umn.edu/gkhome/fetch/sw/hmetis/hmetis-2.0pre1.tar.gz
    - tar xvfz hmetis-2.0pre1.tar.gz
    - ln -sfn hmetis-2.0pre1/Linux-x86_64/hmetis2.0pre1 hmetis
    - sed -i.bak "s/HMETIS_EXECUTABLE \"hmetis\"/HMETIS_EXECUTABLE \"\.\/hmetis\"/g" src/dec_h*partition.cpp
  artifacts:
    expire_in: 10 minutes
    when: on_success
    paths:
      - $CI_PROJECT_DIR

# CMake test (test set: short)
cmake:test:
  stage: test
  needs: ["cmake:build"]
  before_script: []
  script:
    - cd build
    - make gcg_check
    - cd ..
  artifacts:
    when: on_success
    paths:
      - $CI_PROJECT_DIR
    expire_in: 3 days
    

# Makefiles test (test set: short)
make:test:
  stage: test
  needs: ["make:build"]
  before_script: []
  script:
    - make test
  artifacts:
    when: on_success
    paths:
      - check/results/*
    expire_in: 3 days

# Compile documentation and upload to website
docu:
  image: registry.git.or.rwth-aachen.de/docker/gcg-doc:latest
  stage: documentation
  needs: ["cmake:build"]
  script:
    - cd build
    - make gcg_doc -j 4
    - cd ..
    # upload documentation to gcg.or.rwth-aachen.de/dev
    - scp -r doc/html/. gitGCGdoc@orweb.or.rwth-aachen.de:/var/www/gcg-doc-dev
    - ssh gitGCGdoc@orweb.or.rwth-aachen.de "cd /var/www/gcg-doc-dev; chmod -R 755 ./* ; "

testsetreport:
  image: registry.git.or.rwth-aachen.de/docker/gcg-doc:latest
  stage: report
  needs: ["make:test"]
  script:
    - git stash
    - git checkout visu_suite
    - make visu DATADIR=results/
  artifacts:
    when: on_success
    paths:
      - check/reports/*
    expire_in: 3 days

comparisonreport:
  image: registry.git.or.rwth-aachen.de/docker/gcg-doc:latest
  stage: report
  needs: ["make:test"]
  script:
    - sed -i.bak "s/HMETIS_EXECUTABLE \"\.\/hmetis\"/HMETIS_EXECUTABLE \"hmetis\"/g" src/dec_h*partition.cpp
    - git checkout visu_suite
    - make visu DATADIR=results/
  artifacts:
    when: on_success
    paths:
      - check/reports/*
    expire_in: 3 days