# GCG Gitlab CI script

.init_ssh2: &init_ssh2 |
  eval $(ssh-agent -s)
  chmod 700 "$PRIVATE_KEY"
  ls -la "$PRIVATE_KEY"
  ssh-add "$PRIVATE_KEY" > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

stages:
  - gcg_build
  - docu_build

cmake:
  image: registry.git.or.rwth-aachen.de/docker/gcg-doc:latest
  stage: gcg_build
  before_script:
      - *init_ssh2
      - git submodule sync --recursive
      - git submodule update --init --recursive
      - mkdir build
      - cd build
  script:
      - cmake ..
      - make
      - cd ..

documentation:
  image: registry.git.or.rwth-aachen.de/docker/gcg-doc:latest
  stage: docu_build
  before_script:
      - cd build
  script:
      - make gcg_doc -j 4
      - cd ..
      # upload documentation to gcg.or.rwth-aachen.de/dev
      #- scp -r doc/html/. gitGCGdoc@orweb.or.rwth-aachen.de:/var/www/gcg-doc-dev
      #- ssh gitGCGdoc@orweb.or.rwth-aachen.de "cd /var/www/gcg-doc-dev; chmod -R 755 ./* ; "